### ISSUE TITLE
GDAL compile flag --with-openjpeg no longer takes parameter value

### ISSUE THREAD

**Issue by philvarner** [GeographicaGS/Docker-GDAL2#12]
Somewhere between 2.1 and 2.3, the GDAL compile script changed so that the `--with-openjpeg` no longer takes a parameter value. 

The flag
```
--with-openjpeg=$ROOTDIR
```
should now just be
```
--with-openjpeg
```
See:
* [https://trac.osgeo.org/gdal/ticket/7074]
* [https://github.com/OSGeo/gdal/commit/3e762d9c94]

**Comment by cayetanobv** [comment]
Ok @philvarner 
As this change is not affecting to compile process we will include change with next version of GDAL. We also want to update Openjpeg version to v2.3.
Many thanks.
