### ISSUE TITLE
apt-get installs wget and then removes it, but it is never used

### ISSUE THREAD

**Issue by philvarner** [GeographicaGS/Docker-GDAL2#13]
In the first RUN command, wget is installed.  In the third RUN command, it is removed.  But, it is never used between those commands.  My guess is this was left over from when the openjpeg and gdal tgz's were wget'ed instead of ADDed as layers.

**Comment by cayetanobv** [comment]
Ok, thanks @philvarner 
I'm preparing a new release including your suggestion.
