### ISSUE TITLE
Add tag for all GDAL version.

### ISSUE THREAD

**Issue by winsento** [GeographicaGS/Docker-GDAL2#3]
If you add tags on github for each version of GDAL, then on hub.docker.com you can configure the build by tags. In this case, only the image that was changed will be re-builded.

Now build all on each commit:
![image](https://user-images.githubusercontent.com/2316328/27875009-5d4eedac-61ba-11e7-89b7-6828f3b4f299.png)

**Comment by cayetanobv** [comment]
I thought in this issue two years ago. It is very annoying all versions are builded each time a PR against master is merged. I have already configured automated builds with tags, but I haven't tags in git (look at this screenshot):
![image](https://user-images.githubusercontent.com/7315379/27875921-522b1e1e-61b5-11e7-8fcd-9cd320679302.png)

I think I will add tags in the future. Thanks for all.
